apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 14.8.0 # Use the latest PostgreSQL chart version
    helm:
      values: |
        global:
          postgresql:
            postgresqlPostgresqlConfiguration: # Include additional configuration for pg_cron
              shared_preload_libraries: pg_cron
              cron.database_name: mydatabase

        auth:
          postgresPassword: mypassword
          username: myuser
          password: mypassword
          database: mydatabase

        primary:
          extraEnvVars:
            - name: PGCRON_SCHEDULE
              value: "* * * * *"
            - name: PGCRON_COMMAND
              value: "INSERT INTO mytable (content) VALUES ('Row created at ' || NOW());"

          initdbScripts:
            setup.sql: |
              CREATE TABLE IF NOT EXISTS mytable (
                id SERIAL PRIMARY KEY,
                content TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );
              CREATE EXTENSION IF NOT EXISTS pg_cron;

        persistence:
          enabled: true
          size: 10Gi
          storageClass: gp2

  destination:
    namespace: database
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      #prune: true
      selfHeal: true
