# Storage settings (for AWS S3)
configuration:
  provider: aws
  backupStorageLocation:
    name: default
    provider: aws
    bucket: velero-backup-blue
    config:
      region: ap-northeast-2
  volumeSnapshotLocation:
    name: default
    provider: aws
    config:
      region: ap-northeast-2
# Velero schedules for backups
schedules:
  hourly-backup:
    schedule: "0 * * * *"  # Runs every hour at the start of the hour
    template:
      ttl: "72h"  # Backups older than 72 hours will be deleted
      includedNamespaces:
        - "*"
      snapshotVolumes: true
