apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: velero
spec:
  project: default
  source:
    repoURL: https://charts.velero.io
    targetRevision: 2.32.0
    chart: velero
    helm:
      values: |
        # Velero Configuration for S3 Backup
        configuration:
          provider: aws
          backupStorageLocation:
            name: default
            provider: aws
            bucket: velero-backup-blue
            config:
              region: ap-northeast-2
          volumeSnapshotLocation:
            name: default
            provider: aws
            config:
              region: ap-northeast-2
        # Velero schedule for hourly backups
        schedules:
          hourly-backup:
            schedule: "0 * * * *"  # Every hour at the start of the hour
            template:
              ttl: "72h"  # Keep backups for 72 hours
              includedNamespaces:
                - "*"
              snapshotVolumes: true
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
