apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 8.0.0
    helm:
      values: |
        initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.6.0
          volumeMounts:
          - mountPath: /target
            name: plugins
        configuration:
          logLevel: debug
          backupStorageLocations:
          - name: default
            namespace: velero
            provider: aws # Corrected provider
            bucket: velero-backup-bucket-bkuawlz6 # Ensure bucket name matches the actual bucket in AWS
            config:
              region: eu-central-1 # Ensure the AWS region is correct
              prefix: velero-backups
          volumeSnapshotLocations:
          - name: default
            namespace: velero
            provider: aws # Corrected provider
            config:
              region: eu-central-1
        serviceAccount:
          server:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::896781037232:role/velero-server-role-bkuawlz6
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      #prune: true
      selfHeal: true
  hooks:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: velero
    operation: PreSync
