apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: arn:aws:s3:::velero-backup-bucket-dlmrnkp4  # Replace with your bucket name
    prefix: velero-backups
  config:
    region: eu-central-1        # Replace with your AWS region
