#apiVersion: v1
#NEW YALA
apiVersion: v2
appVersion: "1.0"
name: dev-applications
description: App of apps chart for the dev EKS environment.
version: 0.1.0
##NEW YALA
dependencies:
- name: velero
  version: 4.1.3
  repository: https://vmware-tanzu.github.io/helm-charts/
