apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-app
  namespace: postgres
spec:
  project: default
  source:
    repoURL: 'https://github.com/yalafe/terraform-aws-eks-blueprints'  # Replace with your repo URL
    targetRevision: HEAD
    path: patterns/blue-green-upgrade/postgresql  # Replace with the correct path
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
