apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 8.0.0
    helm:
      values: |
        configuration:
          backupStorageLocations:
          - name: default
            provider: aws
            bucket: <VELERO_BUCKET> # Replace with your S3 bucket name
            config:
              region: <AWS_REGION> # Replace with your AWS region
          volumeSnapshotLocations:
          - name: default
            provider: aws
            config:
              region: <AWS_REGION> # Replace with your AWS region
        serviceAccount:
          server:
            annotations:
              eks.amazonaws.com/arn:aws:iam::896781037232:role/velero-role-dlmrnkp4  # Replace with Terraform output or Helm template variable
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
