apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 8.0.0
    helm:
      values: |
        initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.6.0
          volumeMounts:
          - mountPath: /target
            name: plugins
        configuration:
          logLevel: debug
          backupStorageLocations:
          - name: default
            provider: aws
            bucket: arn:aws:s3:::velero-backup-bucket-dlmrnkp4 # Replace with your S3 bucket name
            config:
              region: eu-central-1 # Replace with your AWS region
              prefix: velero-backups
          volumeSnapshotLocations:
          - name: default
            provider: aws
            config:
              region: eu-central-1 # Replace with your AWS region
        serviceAccount:
          server:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::896781037232:role/velero-role-dlmrnkp4  # Replace with Terraform output or Helm template variable
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  hooks:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: velero
    operation: PreSync
