apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: backupvelero
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: arn:aws:s3:::bucket-s3-terraform-bucket # Replace with your S3 bucket name
  config:
    region: ap-northeast-2  # Replace with your AWS region
    s3ForcePathStyle: "true"
    #s3Url: <your-s3-url>  # Replace with your S3 URL if using a custom endpoint

